- hosts: eck
  vars:
    eck_download_url: "https://download.elastic.co/downloads/eck/{{ eck_version | default('1.8.0') }}"
    eck_crds_manifest_url: "{{ eck_download_url }}/crds.yaml"
    eck_operator_manifest_url: "{{ eck_download_url }}/operator.yaml"
  tasks:
  - name: Créer le namespace pour Elastic
    k8s:
      kind: namespace
      name: elastic-system
      state: present

  - name: Installer les CRDS pour ECK
    k8s:                                                                                                                                                                                                             
      definition: '{{ item }}'                                                                                                                                                                                       
    with_items: '{{ lookup("url", eck_crds_manifest_url, split_lines=False) | from_yaml_all | list }}'                                              
    when: item is not none

  - name: Installer l'opérateur ECK
    k8s:                                                                                                                                                                                                             
      definition: '{{ item }}'                                                                                                                                                                                       
    with_items: '{{ lookup("url", eck_operator_manifest_url, split_lines=False) | from_yaml_all | list }}'                                              
    when: item is not none
    register: eck_operator_install_result

  - name: Attendre que l'opérateur soit démarré
    pause:
      minutes: 2
    when: eck_operator_install_result is defined and eck_operator_install_result.changed is defined and eck_operator_install_result.changed

  - name: Ajouter privileged par défaut dans le namespace
    command: oc adm policy add-scc-to-user privileged -z default -n elastic-system
  - name: Ajouter anyuid par défaut dans le namespace
    command: oc adm policy add-scc-to-user anyuid -z default -n elastic-system
  - name: Ajouter hostmount-anyuid par défaut dans le namespace
    command: oc adm policy add-scc-to-user hostmount-anyuid -z default -n elastic-system
  - name: Ajouter hostnetwork par défaut dans le namespace
    command: oc adm policy add-scc-to-user hostnetwork -z default -n elastic-system

  - name: Installer ECK avec l'opérateur.
    include_tasks:
      file: deploy_eck.yml
    when:
      - deploy_eck is defined
      - deploy_eck