- hosts: cert
  tasks:
    - name: Ajouter le certificat CA du Nexus dans la liste de CA des registres de confiance
      block:
      - name: Slurp certificat Nexus
        slurp:
          src: "{{ nexus_registry_ca_cert }}"
        register: slurp_nexus_cert

      - name: Créer le configmap contenant le certificat du registre Nexus
        k8s:
          state: present
          namespace: openshift-config
          definition:
            apiVersion: v1
            kind: ConfigMap
            metadata:
              name: "{{ trusted_registry_configmap }}"
            data:
              nexus3.inspq.qc.ca..5000: "{{ slurp_nexus_cert.content | b64decode }}"
          
      - name: Ajouter le configmap au additionnalTrustedCa du cluster
        k8s:
          definition:
            apiVersion: config.openshift.io/v1
            kind: Image
            metadata:
              name: cluster
            spec:
              additionalTrustedCA:
                name: "{{ trusted_registry_configmap }}"
      when:
        - trusted_registry_configmap is defined
        - nexus_registry_ca_cert is defined

  