- hosts: cert
  tasks:
    - name: Créer le configmap contenant les certificats des registres de confiances
      k8s:
        state: present
        definition: "{{ lookup('template', 'trusted-registry-manifest.yaml.j2') }}"
        
    - name: Ajouter le configmap au additionnalTrustedCa du cluster
      k8s:
        definition:
          apiVersion: config.openshift.io/v1
          kind: Image
          metadata:
            name: cluster
          spec:
            additionalTrustedCA:
              name: "{{ trusted_registry_configmap }}"

      #command: kubectl patch image.config.openshift.io/cluster --patch '{"spec":{"additionalTrustedCA":{"name":"{{ trusted_registry_configmap }}"}}}' --type=merge

  