---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: openebs-exemple-pvc-1
  namespace: default
spec:
  storageClassName: openebs-lvm-localpv-fast
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5G
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: openebs-exemple-pvc-2
  namespace: default
spec:
  storageClassName: openebs-lvm-localpv-fast
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5G
---
apiVersion: v1
kind: Pod
metadata:
  name: hello-lvm-localpv-pod-1
  namespace: default
spec:
  volumes:
  - name: local-storage-1
    persistentVolumeClaim:
      claimName: openebs-exemple-pvc-1
  containers:
  - name: hello-container
    image: busybox
    command:
       - sh
       - -c
       - 'while true; do echo "`date` [`hostname`] Hello from OpenEBS Local PV." >> /mnt/store/greet.txt; sleep $(($RANDOM % 5 + 300)); done'
    volumeMounts:
    - mountPath: /mnt/store
      name: local-storage-1
---
apiVersion: v1
kind: Pod
metadata:
  name: hello-lvm-localpv-pod-2
  namespace: default
spec:
  volumes:
  - name: local-storage-2
    persistentVolumeClaim:
      claimName: openebs-exemple-pvc-2
  containers:
  - name: hello-container
    image: busybox
    command:
       - sh
       - -c
       - 'while true; do echo "`date` [`hostname`] Hello from OpenEBS Local PV." >> /mnt/store/greet.txt; sleep $(($RANDOM % 5 + 300)); done'
    volumeMounts:
    - mountPath: /mnt/store
      name: local-storage-2     