apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-lvm-localpv-fast
parameters:
  storage: "lvm"
  volgroup: "fastvg"
  csi.storage.k8s.io/fstype: xfs
provisioner: local.csi.openebs.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
- matchLabelExpressions:
  - key: kubernetes.io/hostname
    values:
      - kube05
      - kube06
      - kube07
      - kube08
      - kube09
      - kube10