- hosts: cert
  vars:
    cert_manager_namespace: cert-manager
    cert_manager_version: v1.5.3
    cert_manager_helm_repo_name: jetstack 
    cert_manager_helm_repo_url: https://charts.jetstack.io
    cert_manager_helm_release_name: cert-manager
    cert_manager_helm_chart: jetstack/cert-manager
    cert_manager_manifest_url: "https://github.com/jetstack/cert-manager/releases/download/{{ cert_manager_version }}/cert-manager.yaml"
  tasks:
  - name: installer les pré-requis python
    pip:
      name:
        - openshift
  - name: Installer le référentiel Helm Jetstack pour cert-manager
    community.kubernetes.helm_repository:
      name: "{{ cert_manager_helm_repo_name }}"
      repo_url: "{{ cert_manager_helm_repo_url }}"
      state: present
  - name: Créer le namespace pour cert-manager
    k8s:
      kind: namespace
      name: "{{ cert_manager_namespace }}"
  - name: Installer cert-manager
    community.kubernetes.helm:                                                                                                                                                                                                             
      name: "{{ cert_manager_helm_release_name }}"
      chart_ref: "{{ cert_manager_helm_chart }}"
      release_namespace: "{{ cert_manager_namespace }}"
      release_state: present
      chart_version: "{{ cert_manager_version }}"
      create_namespace: yes
      release_values:
        installCRDs: true
