---
kind: Project
apiVersion: project.openshift.io/v1
metadata:
  name: keycloak
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kc-postgres-pod-cluster-admin
subjects:
  - kind: ServiceAccount
    name: postgres-pod
    namespace: keycloak
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
---
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: acid-keycloak-cluster
  namespace: keycloak
spec:
  teamId: "acid"
  volume:
      size: '20Gi'
      storageClass: openebs-lvm-localpv-fast
  numberOfInstances: 2
  users:
    keycloak:  # database owner
    - superuser
    - createdb
    keycloak_user: []  # role for application foo
  databases:
    keycloak: keycloak  # dbname: owner
  preparedDatabases: {}
  postgresql:
    version: "13"
