apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: kube-lacave-apm-server
  namespace: elastic-system
spec:
  version: 7.9.2
  count: 1
  elasticsearchRef:
    name: kube-lacave-elasticsearch
  kibanaRef:
    name: kube-lacave-kibana