apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
  namespace: default
spec:
  kafka:
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: '3.0'
      inter.broker.protocol.version: '3.0'
    storage:
      type: persistent-claim
      size: 1Gi
      deleteClaim: true
      class: openebs-lvm-localpv-slow
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        port: 39092
        type: nodeport
        tls: false
        configuration:
          brokers:
          - broker: 0
            advertisedHost: kube06.lacave.info
            nodePort: 31092
          - broker: 1
            advertizedHost: kube07.lacave.info
            nodePort: 31093
          - broker: 2
            advertizedHost: kube08.lacave.info
            nodePort: 31094
    template:
      pod:
        securityContext:
          runAsUser: 0
          fsGroup: 0
    version: 3.0.0
    replicas: 3
    rack:
      topologyKey: kubernetes.io/hostname
  entityOperator:
    topicOperator: {}
    userOperator: {}
  zookeeper:
    storage:
      type: persistent-claim
      size: 1Gi
      class: openebs-lvm-localpv-slow
      deleteClaim: true
    template:
      pod:
        securityContext:
          runAsUser: 0
          fsGroup: 0
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: strimzi.io/name
                      operator: In
                      values:
                        - my-cluster-zookeeper
                topologyKey: kubernetes.io/hostname
    replicas: 3